// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs1L3DDvlitDMWBU5hgqCwI2NW_DDkhbo',
    appId: '1:1042729786432:android:a16e15fccf4ce2dc5b53a5',
    messagingSenderId: '1042729786432',
    projectId: 'our-mindpark-app',
    storageBucket: 'our-mindpark-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnNVzTso2Ikj5QnXbXw-LR3la_BjFjP7w',
    appId: '1:1042729786432:ios:8404bb1b9177c9995b53a5',
    messagingSenderId: '1042729786432',
    projectId: 'our-mindpark-app',
    storageBucket: 'our-mindpark-app.appspot.com',
    androidClientId:
        '1042729786432-5iaofl5vi7jheibn48tnqsslem1t2udc.apps.googleusercontent.com',
    iosClientId:
        '1042729786432-v76c170l2lhc1ep3cdp1e8qfpertvupj.apps.googleusercontent.com',
    iosBundleId: 'com.mindpark.app',
  );
}
