List<List<Map<String, dynamic>>> easyNodeList = [
  [
    {
      'number': 1,
      'xPosition': 0.5,
      'yPosition': 0.3,
      'text': '1',
      'index': 0,
    },
    {
      'number': 2,
      'xPosition': 0.37,
      'yPosition': 0.39,
      'text': 'A',
      'index': 1,
    },
    {
      'number': 3,
      'xPosition': 0.21,
      'yPosition': 0.3,
      'text': '2',
      'index': 2,
    },
    {
      'number': 4,
      'xPosition': 0.67,
      'yPosition': 0.2,
      'text': 'B',
      'index': 3,
    },
    {
      'number': 5,
      'xPosition': 0.62,
      'yPosition': 0.44,
      'text': '3',
      'index': 4,
    },
    {
      'number': 6,
      'xPosition': 0.49,
      'yPosition': 0.51,
      'text': 'C',
      'index': 5,
    },
  ],
  [
    {
      'number': 1,
      'xPosition': 0.18,
      'yPosition': 0.18,
      'text': '1',
      'index': 0,
    },
    {
      'number': 2,
      'xPosition': 0.54,
      'yPosition': 0.11,
      'text': 'A',
      'index': 1,
    },
    {
      'number': 3,
      'xPosition': 0.45,
      'yPosition': 0.53,
      'text': '2',
      'index': 2,
    },
    {
      'number': 4,
      'xPosition': 0.25,
      'yPosition': 0.63,
      'text': 'B',
      'index': 3,
    },
    {
      'number': 5,
      'xPosition': 0.64,
      'yPosition': 0.64,
      'text': '3',
      'index': 4,
    },
    {
      'number': 6,
      'xPosition': 0.80,
      'yPosition': 0.50,
      'text': 'C',
      'index': 5,
    },
  ],
  [
    {
      'number': 1,
      'xPosition': 0.40,
      'yPosition': 0.25,
      'text': '1',
      'index': 0,
    },
    {
      'number': 2,
      'xPosition': 0.30,
      'yPosition': 0.55,
      'text': 'A',
      'index': 1,
    },
    {
      'number': 3,
      'xPosition': 0.50,
      'yPosition': 0.70,
      'text': '2',
      'index': 2,
    },
    {
      'number': 4,
      'xPosition': 0.65,
      'yPosition': 0.35,
      'text': 'B',
      'index': 3,
    },
    {
      'number': 5,
      'xPosition': 0.60,
      'yPosition': 0.10,
      'text': '3',
      'index': 4,
    },
    {
      'number': 6,
      'xPosition': 0.45,
      'yPosition': 0.45,
      'text': 'C',
      'index': 5,
    },
  ]
];
