List<List<Map<String, dynamic>>> hardNodeList = [
  [
    {
      "number": 1,
      "xPosition": 0.43,
      "yPosition": 0.20,
      "text": '1',
      "index": 0,
    },
    {
      "number": 2,
      "xPosition": 0.50,
      "yPosition": 0.35,
      "text": '2',
      "index": 1,
    },
    {
      "number": 3,
      "xPosition": 0.48,
      "yPosition": 0.08,
      "text": '3',
      "index": 2,
    },
    {
      "number": 4,
      "xPosition": 0.32,
      "yPosition": 0.20,
      "text": '4',
      "index": 3,
    },
    {
      "number": 5,
      "xPosition": 0.34,
      "yPosition": 0.60,
      "text": '5',
      "index": 4,
    },
    {
      "number": 6,
      "xPosition": 0.39,
      "yPosition": 0.42,
      "text": '6',
      "index": 5,
    },
    {
      "number": 7,
      "xPosition": 0.53,
      "yPosition": 0.58,
      "text": '7',
      "index": 6,
    },
    {
      "number": 8,
      "xPosition": 0.65,
      "yPosition": 0.60,
      "text": '8',
      "index": 7,
    },
    {
      "number": 9,
      "xPosition": 0.72,
      "yPosition": 0.46,
      "text": '9',
      "index": 8,
    },
    {
      "number": 10,
      "xPosition": 0.60,
      "yPosition": 0.35,
      "text": '10',
      "index": 9
    },
    {
      "number": 11,
      "xPosition": 0.66,
      "yPosition": 0.11,
      "text": '11',
      "index": 10,
    },
    {
      "number": 12,
      "xPosition": 0.88,
      "yPosition": 0.70,
      "text": '12',
      "index": 11,
    },
    {
      "number": 13,
      "xPosition": 0.42,
      "yPosition": 0.75,
      "text": '13',
      "index": 12,
    },
    {
      "number": 14,
      "xPosition": 0.22,
      "yPosition": 0.75,
      "text": '14',
      "index": 13,
    },
    {
      "number": 15,
      "xPosition": 0.04,
      "yPosition": 0.75,
      "text": '15',
      "index": 14,
    },
    {
      "number": 16,
      "xPosition": 0.14,
      "yPosition": 0.60,
      "text": '16',
      "index": 15,
    },
    {
      "number": 17,
      "xPosition": 0.04,
      "yPosition": 0.45,
      "text": '17',
      "index": 16,
    },
    {
      "number": 18,
      "xPosition": 0.22,
      "yPosition": 0.46,
      "text": '18',
      "index": 17,
    },
    {
      "number": 19,
      "xPosition": 0.04,
      "yPosition": 0.17,
      "text": '19',
      "index": 18,
    },
    {
      "number": 20,
      "xPosition": 0.20,
      "yPosition": 0.22,
      "text": '20',
      "index": 19,
    },
    {
      "number": 21,
      "xPosition": 0.14,
      "yPosition": 0.03,
      "text": '21',
      "index": 20,
    },
    {
      "number": 22,
      "xPosition": 0.36,
      "yPosition": 0.00,
      "text": '22',
      "index": 21,
    },
    {
      "number": 23,
      "xPosition": 0.77,
      "yPosition": 0.00,
      "text": '23',
      "index": 22,
    },
    {
      "number": 24,
      "xPosition": 0.78,
      "yPosition": 0.18,
      "text": '24',
      "index": 23,
    },
    {
      "number": 25,
      "xPosition": 0.83,
      "yPosition": 0.39,
      "text": '25',
      "index": 24,
    }
  ],
  [
    {
      "number": 1,
      "xPosition": 0.42,
      "yPosition": 0.35,
      "text": '1',
      "index": 0,
    },
    {
      "number": 2,
      "xPosition": 0.33,
      "yPosition": 0.21,
      "text": '2',
      "index": 1,
    },
    {
      "number": 3,
      "xPosition": 0.65,
      "yPosition": 0.21,
      "text": '3',
      "index": 2,
    },
    {
      "number": 4,
      "xPosition": 0.65,
      "yPosition": 0.40,
      "text": '4',
      "index": 3,
    },
    {
      "number": 5,
      "xPosition": 0.33,
      "yPosition": 0.50,
      "text": '5',
      "index": 4,
    },
    {
      "number": 6,
      "xPosition": 0.45,
      "yPosition": 0.60,
      "text": '6',
      "index": 5,
    },
    {
      "number": 7,
      "xPosition": 0.25,
      "yPosition": 0.70,
      "text": '7',
      "index": 6,
    },
    {
      "number": 8,
      "xPosition": 0.15,
      "yPosition": 0.24,
      "text": '8',
      "index": 7,
    },
    {
      "number": 9,
      "xPosition": 0.21,
      "yPosition": 0.10,
      "text": '9',
      "index": 8,
    },
    {
      "number": 10,
      "xPosition": 0.33,
      "yPosition": 0.05,
      "text": '10',
      "index": 9
    },
    {
      "number": 11,
      "xPosition": 0.48,
      "yPosition": 0.08,
      "text": '11',
      "index": 10,
    },
    {
      "number": 12,
      "xPosition": 0.75,
      "yPosition": 0.07,
      "text": '12',
      "index": 11,
    },
    {
      "number": 13,
      "xPosition": 0.85,
      "yPosition": 0.11,
      "text": '13',
      "index": 12,
    },
    {
      "number": 14,
      "xPosition": 0.85,
      "yPosition": 0.30,
      "text": '14',
      "index": 13,
    },
    {
      "number": 15,
      "xPosition": 0.72,
      "yPosition": 0.55,
      "text": '15',
      "index": 14,
    },
    {
      "number": 16,
      "xPosition": 0.85,
      "yPosition": 0.65,
      "text": '16',
      "index": 15,
    },
    {
      "number": 17,
      "xPosition": 0.72,
      "yPosition": 0.75,
      "text": '17',
      "index": 16,
    },
    {
      "number": 18,
      "xPosition": 0.62,
      "yPosition": 0.65,
      "text": '18',
      "index": 17,
    },
    {
      "number": 19,
      "xPosition": 0.55,
      "yPosition": 0.55,
      "text": '19',
      "index": 18,
    },
    {
      "number": 20,
      "xPosition": 0.55,
      "yPosition": 0.75,
      "text": '20',
      "index": 19,
    },
    {
      "number": 21,
      "xPosition": 0.40,
      "yPosition": 0.75,
      "text": '21',
      "index": 20,
    },
    {
      "number": 22,
      "xPosition": 0.15,
      "yPosition": 0.50,
      "text": '22',
      "index": 21,
    },
    {
      "number": 23,
      "xPosition": 0.15,
      "yPosition": 0.75,
      "text": '23',
      "index": 22,
    },
    {
      "number": 24,
      "xPosition": 0.05,
      "yPosition": 0.75,
      "text": '24',
      "index": 23,
    },
    {
      "number": 25,
      "xPosition": 0.05,
      "yPosition": 0.45,
      "text": '25',
      "index": 24,
    }
  ],
  [
    {
      "number": 1,
      "xPosition": 0.30,
      "yPosition": 0.50,
      "text": '1',
      "index": 0,
    },
    {
      "number": 2,
      "xPosition": 0.20,
      "yPosition": 0.50,
      "text": '2',
      "index": 1,
    },
    {
      "number": 3,
      "xPosition": 0.20,
      "yPosition": 0.75,
      "text": '3',
      "index": 2,
    },
    {
      "number": 4,
      "xPosition": 0.30,
      "yPosition": 0.70,
      "text": '4',
      "index": 3,
    },
    {
      "number": 5,
      "xPosition": 0.40,
      "yPosition": 0.75,
      "text": '5',
      "index": 4,
    },
    {
      "number": 6,
      "xPosition": 0.55,
      "yPosition": 0.50,
      "text": '6',
      "index": 5,
    },
    {
      "number": 7,
      "xPosition": 0.42,
      "yPosition": 0.50,
      "text": '7',
      "index": 6,
    },
    {
      "number": 8,
      "xPosition": 0.42,
      "yPosition": 0.30,
      "text": '8',
      "index": 7,
    },
    {
      "number": 9,
      "xPosition": 0.30,
      "yPosition": 0.30,
      "text": '9',
      "index": 8,
    },
    {
      "number": 10,
      "xPosition": 0.20,
      "yPosition": 0.32,
      "text": '10',
      "index": 9
    },
    {
      "number": 11,
      "xPosition": 0.10,
      "yPosition": 0.50,
      "text": '11',
      "index": 10,
    },
    {
      "number": 12,
      "xPosition": 0.10,
      "yPosition": 0.75,
      "text": '12',
      "index": 11,
    },
    {
      "number": 13,
      "xPosition": 0.02,
      "yPosition": 0.75,
      "text": '13',
      "index": 12,
    },
    {
      "number": 14,
      "xPosition": 0.02,
      "yPosition": 0.50,
      "text": '14',
      "index": 13,
    },
    {
      "number": 15,
      "xPosition": 0.08,
      "yPosition": 0.30,
      "text": '15',
      "index": 14,
    },
    {
      "number": 16,
      "xPosition": 0.03,
      "yPosition": 0.15,
      "text": '16',
      "index": 15,
    },
    {
      "number": 17,
      "xPosition": 0.15,
      "yPosition": 0.02,
      "text": '17',
      "index": 16,
    },
    {
      "number": 18,
      "xPosition": 0.25,
      "yPosition": 0.15,
      "text": '18',
      "index": 17,
    },
    {
      "number": 19,
      "xPosition": 0.47,
      "yPosition": 0.15,
      "text": '19',
      "index": 18,
    },
    {
      "number": 20,
      "xPosition": 0.50,
      "yPosition": 0.65,
      "text": '20',
      "index": 19,
    },
    {
      "number": 21,
      "xPosition": 0.65,
      "yPosition": 0.60,
      "text": '21',
      "index": 20,
    },
    {
      "number": 22,
      "xPosition": 0.65,
      "yPosition": 0.40,
      "text": '22',
      "index": 21,
    },
    {
      "number": 23,
      "xPosition": 0.55,
      "yPosition": 0.30,
      "text": '23',
      "index": 22,
    },
    {
      "number": 24,
      "xPosition": 0.70,
      "yPosition": 0.15,
      "text": '24',
      "index": 23,
    },
    {
      "number": 25,
      "xPosition": 0.80,
      "yPosition": 0.65,
      "text": '25',
      "index": 24,
    }
  ]
];
