List<List<Map<String, dynamic>>> hardNodeList = [
  [
    {
      'number': 1,
      'xPosition': 0.5,
      'yPosition': 0.3,
      'text': '1',
      'index': 0,
    },
    {
      'number': 2,
      'xPosition': 0.37,
      'yPosition': 0.39,
      'text': 'A',
      'index': 1,
    },
    {
      'number': 3,
      'xPosition': 0.21,
      'yPosition': 0.3,
      'text': '2',
      'index': 2,
    },
    {
      'number': 4,
      'xPosition': 0.67,
      'yPosition': 0.2,
      'text': 'B',
      'index': 3,
    },
    {
      'number': 5,
      'xPosition': 0.62,
      'yPosition': 0.44,
      'text': '3',
      'index': 4,
    },
    {
      'number': 6,
      'xPosition': 0.49,
      'yPosition': 0.51,
      'text': 'C',
      'index': 5,
    },
    {
      'number': 7,
      'xPosition': 0.75,
      'yPosition': 0.5,
      'text': '4',
      'index': 6,
    },
    {
      'number': 8,
      'xPosition': 0.73,
      'yPosition': 0.65,
      'text': 'D',
      'index': 7,
    },
    {
      'number': 9,
      'xPosition': 0.56,
      'yPosition': 0.65,
      'text': '5',
      'index': 8,
    },
    {
      'number': 10,
      'xPosition': 0.15,
      'yPosition': 0.68,
      'text': 'E',
      'index': 9,
    },
    {
      'number': 11,
      'xPosition': 0.25,
      'yPosition': 0.54,
      'text': '6',
      'index': 10,
    },
    {
      'number': 12,
      'xPosition': 0.1,
      'yPosition': 0.33,
      'text': 'F',
      'index': 11,
    },
    {
      'number': 13,
      'xPosition': 0.24,
      'yPosition': 0.07,
      'text': '7',
      'index': 12,
    },
    {
      'number': 14,
      'xPosition': 0.38,
      'yPosition': 0.08,
      'text': 'G',
      'index': 13,
    },
    {
      'number': 15,
      'xPosition': 0.55,
      'yPosition': 0.12,
      'text': '8',
      'index': 14,
    },
    {
      'number': 16,
      'xPosition': 0.77,
      'yPosition': 0.01,
      'text': 'H',
      'index': 15,
    },
    {
      'number': 17,
      'xPosition': 0.82,
      'yPosition': 0.28,
      'text': '9',
      'index': 16,
    },
    {
      'number': 18,
      'xPosition': 0.84,
      'yPosition': 0.48,
      'text': 'I',
      'index': 17,
    },
    {
      'number': 19,
      'xPosition': 0.82,
      'yPosition': 0.75,
      'text': '10',
      'index': 18,
    },
    {
      'number': 20,
      'xPosition': 0.43,
      'yPosition': 0.78,
      'text': 'J',
      'index': 19,
    },
    {
      'number': 21,
      'xPosition': 0.04,
      'yPosition': 0.78,
      'text': '11',
      'index': 20,
    },
    {
      'number': 22,
      'xPosition': 0.1,
      'yPosition': 0.55,
      'text': 'K',
      'index': 21,
    },
    {
      'number': 23,
      'xPosition': 0.01,
      'yPosition': 0.13,
      'text': '12',
      'index': 22,
    },
    {
      'number': 24,
      'xPosition': 0.1,
      'yPosition': 0.01,
      'text': 'L',
      'index': 23,
    },
    {
      'number': 25,
      'xPosition': 0.50,
      'yPosition': 0.001,
      'text': '13',
      'index': 24,
    }
  ],
  // [
  //   {
  //     "number": 1,
  //     "xPosition": 0.42,
  //     "yPosition": 0.35,
  //     "text": '1',
  //     "index": 0,
  //   },
  //   {
  //     "number": 2,
  //     "xPosition": 0.33,
  //     "yPosition": 0.21,
  //     "text": 'A',
  //     "index": 1,
  //   },
  //   {
  //     "number": 3,
  //     "xPosition": 0.65,
  //     "yPosition": 0.21,
  //     "text": '2',
  //     "index": 2,
  //   },
  //   {
  //     "number": 4,
  //     "xPosition": 0.65,
  //     "yPosition": 0.40,
  //     "text": 'B',
  //     "index": 3,
  //   },
  //   {
  //     "number": 5,
  //     "xPosition": 0.33,
  //     "yPosition": 0.50,
  //     "text": '3',
  //     "index": 4,
  //   },
  //   {
  //     "number": 6,
  //     "xPosition": 0.45,
  //     "yPosition": 0.60,
  //     "text": 'C',
  //     "index": 5,
  //   },
  //   {
  //     "number": 7,
  //     "xPosition": 0.25,
  //     "yPosition": 0.70,
  //     "text": '4',
  //     "index": 6,
  //   },
  //   {
  //     "number": 8,
  //     "xPosition": 0.15,
  //     "yPosition": 0.24,
  //     "text": 'D',
  //     "index": 7,
  //   },
  //   {
  //     "number": 9,
  //     "xPosition": 0.21,
  //     "yPosition": 0.10,
  //     "text": '5',
  //     "index": 8,
  //   },
  //   {
  //     "number": 10,
  //     "xPosition": 0.33,
  //     "yPosition": 0.05,
  //     "text": 'E',
  //     "index": 9
  //   },
  //   {
  //     "number": 11,
  //     "xPosition": 0.48,
  //     "yPosition": 0.08,
  //     "text": '6',
  //     "index": 10,
  //   },
  //   {
  //     "number": 12,
  //     "xPosition": 0.75,
  //     "yPosition": 0.07,
  //     "text": 'F',
  //     "index": 11,
  //   },
  //   {
  //     "number": 13,
  //     "xPosition": 0.85,
  //     "yPosition": 0.11,
  //     "text": '7',
  //     "index": 12,
  //   },
  //   {
  //     "number": 14,
  //     "xPosition": 0.85,
  //     "yPosition": 0.30,
  //     "text": 'G',
  //     "index": 13,
  //   },
  //   {
  //     "number": 15,
  //     "xPosition": 0.72,
  //     "yPosition": 0.55,
  //     "text": '8',
  //     "index": 14,
  //   },
  //   {
  //     "number": 16,
  //     "xPosition": 0.85,
  //     "yPosition": 0.65,
  //     "text": 'H',
  //     "index": 15,
  //   },
  //   {
  //     "number": 17,
  //     "xPosition": 0.72,
  //     "yPosition": 0.75,
  //     "text": '9',
  //     "index": 16,
  //   },
  //   {
  //     "number": 18,
  //     "xPosition": 0.62,
  //     "yPosition": 0.65,
  //     "text": 'I',
  //     "index": 17,
  //   },
  //   {
  //     "number": 19,
  //     "xPosition": 0.55,
  //     "yPosition": 0.55,
  //     "text": '10',
  //     "index": 18,
  //   },
  //   {
  //     "number": 20,
  //     "xPosition": 0.55,
  //     "yPosition": 0.75,
  //     "text": 'J',
  //     "index": 19,
  //   },
  //   {
  //     "number": 21,
  //     "xPosition": 0.40,
  //     "yPosition": 0.75,
  //     "text": '11',
  //     "index": 20,
  //   },
  //   {
  //     "number": 22,
  //     "xPosition": 0.15,
  //     "yPosition": 0.50,
  //     "text": 'K',
  //     "index": 21,
  //   },
  //   {
  //     "number": 23,
  //     "xPosition": 0.15,
  //     "yPosition": 0.75,
  //     "text": '12',
  //     "index": 22,
  //   },
  //   {
  //     "number": 24,
  //     "xPosition": 0.05,
  //     "yPosition": 0.75,
  //     "text": 'L',
  //     "index": 23,
  //   },
  //   {
  //     "number": 25,
  //     "xPosition": 0.05,
  //     "yPosition": 0.45,
  //     "text": '13',
  //     "index": 24,
  //   }
  // ],
  // [
  //   {
  //     "number": 1,
  //     "xPosition": 0.30,
  //     "yPosition": 0.50,
  //     "text": '1',
  //     "index": 0,
  //   },
  //   {
  //     "number": 2,
  //     "xPosition": 0.20,
  //     "yPosition": 0.50,
  //     "text": 'A',
  //     "index": 1,
  //   },
  //   {
  //     "number": 3,
  //     "xPosition": 0.20,
  //     "yPosition": 0.75,
  //     "text": '2',
  //     "index": 2,
  //   },
  //   {
  //     "number": 4,
  //     "xPosition": 0.30,
  //     "yPosition": 0.70,
  //     "text": 'B',
  //     "index": 3,
  //   },
  //   {
  //     "number": 5,
  //     "xPosition": 0.40,
  //     "yPosition": 0.75,
  //     "text": '3',
  //     "index": 4,
  //   },
  //   {
  //     "number": 6,
  //     "xPosition": 0.55,
  //     "yPosition": 0.50,
  //     "text": 'C',
  //     "index": 5,
  //   },
  //   {
  //     "number": 7,
  //     "xPosition": 0.42,
  //     "yPosition": 0.50,
  //     "text": '4',
  //     "index": 6,
  //   },
  //   {
  //     "number": 8,
  //     "xPosition": 0.42,
  //     "yPosition": 0.30,
  //     "text": 'D',
  //     "index": 7,
  //   },
  //   {
  //     "number": 9,
  //     "xPosition": 0.30,
  //     "yPosition": 0.30,
  //     "text": '5',
  //     "index": 8,
  //   },
  //   {
  //     "number": 10,
  //     "xPosition": 0.20,
  //     "yPosition": 0.32,
  //     "text": 'E',
  //     "index": 9
  //   },
  //   {
  //     "number": 11,
  //     "xPosition": 0.10,
  //     "yPosition": 0.50,
  //     "text": '6',
  //     "index": 10,
  //   },
  //   {
  //     "number": 12,
  //     "xPosition": 0.10,
  //     "yPosition": 0.75,
  //     "text": 'F',
  //     "index": 11,
  //   },
  //   {
  //     "number": 13,
  //     "xPosition": 0.02,
  //     "yPosition": 0.75,
  //     "text": '7',
  //     "index": 12,
  //   },
  //   {
  //     "number": 14,
  //     "xPosition": 0.02,
  //     "yPosition": 0.50,
  //     "text": 'G',
  //     "index": 13,
  //   },
  //   {
  //     "number": 15,
  //     "xPosition": 0.08,
  //     "yPosition": 0.30,
  //     "text": '8',
  //     "index": 14,
  //   },
  //   {
  //     "number": 16,
  //     "xPosition": 0.03,
  //     "yPosition": 0.15,
  //     "text": 'H',
  //     "index": 15,
  //   },
  //   {
  //     "number": 17,
  //     "xPosition": 0.15,
  //     "yPosition": 0.02,
  //     "text": '9',
  //     "index": 16,
  //   },
  //   {
  //     "number": 18,
  //     "xPosition": 0.25,
  //     "yPosition": 0.15,
  //     "text": 'I',
  //     "index": 17,
  //   },
  //   {
  //     "number": 19,
  //     "xPosition": 0.47,
  //     "yPosition": 0.15,
  //     "text": '10',
  //     "index": 18,
  //   },
  //   {
  //     "number": 20,
  //     "xPosition": 0.50,
  //     "yPosition": 0.65,
  //     "text": 'J',
  //     "index": 19,
  //   },
  //   {
  //     "number": 21,
  //     "xPosition": 0.65,
  //     "yPosition": 0.60,
  //     "text": '11',
  //     "index": 20,
  //   },
  //   {
  //     "number": 22,
  //     "xPosition": 0.65,
  //     "yPosition": 0.40,
  //     "text": 'K',
  //     "index": 21,
  //   },
  //   {
  //     "number": 23,
  //     "xPosition": 0.55,
  //     "yPosition": 0.30,
  //     "text": '12',
  //     "index": 22,
  //   },
  //   {
  //     "number": 24,
  //     "xPosition": 0.70,
  //     "yPosition": 0.15,
  //     "text": 'L',
  //     "index": 23,
  //   },
  //   {
  //     "number": 25,
  //     "xPosition": 0.80,
  //     "yPosition": 0.65,
  //     "text": '13',
  //     "index": 24,
  //   }
  // ]
];
