// medium_config.dart
final List<String> mediumImages = [
  'assets/images/sad/sad_1.jpg',
  'assets/images/sad/sad_2.jpg',
  'assets/images/sad/sad_3.jpg',
  'assets/images/sad/sad_4.jpg',
  'assets/images/sad/sad_5.jpg',
  'assets/images/sad/sad_6.jpg',
  'assets/images/happy/happy_1.jpg',
  'assets/images/happy/happy_2.jpg',
  'assets/images/happy/happy_3.jpg',
  'assets/images/happy/happy_4.jpg',
  'assets/images/happy/happy_5.jpg',
  'assets/images/happy/happy_6.jpg',
  'assets/images/angry/angry_1.jpg',
  'assets/images/angry/angry_2.jpg',
  'assets/images/angry/angry_3.jpg',
  'assets/images/angry/angry_4.jpg',
  'assets/images/angry/angry_5.jpg',
  'assets/images/angry/angry_6.jpg',
  'assets/images/surprise/surprise_1.jpg',
  'assets/images/surprise/surprise_2.jpg',
  'assets/images/surprise/surprise_3.jpg',
  'assets/images/surprise/surprise_4.jpg',
  'assets/images/surprise/surprise_5.jpg',
  'assets/images/surprise/surprise_6.jpg',
];

final Map<String, String> mediumEmotions = {
  'assets/images/sad/sad_1.jpg': "Sad",
  'assets/images/sad/sad_2.jpg': "Sad",
  'assets/images/sad/sad_3.jpg': "Sad",
  'assets/images/sad/sad_4.jpg': "Sad",
  'assets/images/sad/sad_5.jpg': "Sad",
  'assets/images/sad/sad_6.jpg': "Sad",
  'assets/images/happy/happy_1.jpg': "Happy",
  'assets/images/happy/happy_2.jpg': "Happy",
  'assets/images/happy/happy_3.jpg': "Happy",
  'assets/images/happy/happy_4.jpg': "Happy",
  'assets/images/happy/happy_5.jpg': "Happy",
  'assets/images/happy/happy_6.jpg': "Happy",
  "assets/images/angry/angry_1.jpg": "Angry",
  'assets/images/angry/angry_2.jpg': "Angry",
  'assets/images/angry/angry_3.jpg': "Angry",
  'assets/images/angry/angry_4.jpg': "Angry",
  'assets/images/angry/angry_5.jpg': "Angry",
  'assets/images/angry/angry_6.jpg': "Angry",
  'assets/images/surprise/surprise_1.jpg': "Surprise",
  'assets/images/surprise/surprise_2.jpg': "Surprise",
  'assets/images/surprise/surprise_3.jpg': "Surprise",
  'assets/images/surprise/surprise_4.jpg': "Surprise",
  'assets/images/surprise/surprise_5.jpg': "Surprise",
  'assets/images/surprise/surprise_6.jpg': "Surprise",
};
