final List<String> images = [
  'assets/images/angry/angry_1.jpg',
  'assets/images/angry/angry_2.jpg',
  'assets/images/angry/angry_3.jpg',
  'assets/images/angry/angry_4.jpg',
  'assets/images/angry/angry_5.jpg',
  'assets/images/angry/angry_6.jpg',
  'assets/images/angry/angry_7.jpg',
  'assets/images/angry/angry_8.jpg',
  'assets/images/fear/fear_1.jpg',
  'assets/images/fear/fear_2.jpg',
  'assets/images/fear/fear_3.jpg',
  'assets/images/fear/fear_4.jpg',
  'assets/images/fear/fear_5.jpg',
  'assets/images/fear/fear_6.jpg',
  'assets/images/fear/fear_7.jpg',
  'assets/images/fear/fear_8.jpg',
  'assets/images/happy/happy_1.jpg',
  'assets/images/happy/happy_2.jpg',
  'assets/images/happy/happy_3.jpg',
  'assets/images/happy/happy_4.jpg',
  'assets/images/happy/happy_5.jpg',
  'assets/images/happy/happy_6.jpg',
  'assets/images/happy/happy_7.jpg',
  'assets/images/happy/happy_8.jpg',
  'assets/images/neutral/neutral_1.jpg',
  'assets/images/neutral/neutral_2.jpg',
  'assets/images/neutral/neutral_3.jpg',
  'assets/images/neutral/neutral_4.jpg',
  'assets/images/neutral/neutral_5.jpg',
  'assets/images/neutral/neutral_6.jpg',
  'assets/images/neutral/neutral_7.jpg',
  'assets/images/neutral/neutral_8.jpg',
  'assets/images/sad/sad_1.jpg',
  'assets/images/sad/sad_2.jpg',
  'assets/images/sad/sad_3.jpg',
  'assets/images/sad/sad_4.jpg',
  'assets/images/sad/sad_5.jpg',
  'assets/images/sad/sad_6.jpg',
  'assets/images/sad/sad_7.jpg',
  'assets/images/sad/sad_8.jpg',
  'assets/images/surprise/surprise_1.jpg',
  'assets/images/surprise/surprise_2.jpg',
  'assets/images/surprise/surprise_3.jpg',
  'assets/images/surprise/surprise_4.jpg',
  'assets/images/surprise/surprise_5.jpg',
  'assets/images/surprise/surprise_6.jpg',
  'assets/images/surprise/surprise_7.jpg',
  'assets/images/surprise/surprise_8.jpg',
];
final Map<String, String> imageToEmotion = {
  "assets/images/angry/angry_1.jpg": "Angry",
  'assets/images/angry/angry_2.jpg': "Angry",
  'assets/images/angry/angry_3.jpg': "Angry",
  'assets/images/angry/angry_4.jpg': "Angry",
  'assets/images/angry/angry_5.jpg': "Angry",
  'assets/images/angry/angry_6.jpg': "Angry",
  'assets/images/angry/angry_7.jpg': "Angry",
  'assets/images/angry/angry_8.jpg': "Angry",
  'assets/images/happy/happy_1.jpg': "Happy",
  'assets/images/happy/happy_2.jpg': "Happy",
  'assets/images/happy/happy_3.jpg': "Happy",
  'assets/images/happy/happy_4.jpg': "Happy",
  'assets/images/happy/happy_5.jpg': "Happy",
  'assets/images/happy/happy_6.jpg': "Happy",
  'assets/images/happy/happy_7.jpg': "Happy",
  'assets/images/happy/happy_8.jpg': "Happy",
  'assets/images/fear/fear_1.jpg': "Fear",
  'assets/images/fear/fear_2.jpg': "Fear",
  'assets/images/fear/fear_3.jpg': "Fear",
  'assets/images/fear/fear_4.jpg': "Fear",
  'assets/images/fear/fear_5.jpg': "Fear",
  'assets/images/fear/fear_6.jpg': "Fear",
  'assets/images/fear/fear_7.jpg': "Fear",
  'assets/images/fear/fear_8.jpg': "Fear",
  'assets/images/neutral/neutral_1.jpg': "Neutral",
  'assets/images/neutral/neutral_2.jpg': "Neutral",
  'assets/images/neutral/neutral_3.jpg': "Neutral",
  'assets/images/neutral/neutral_4.jpg': "Neutral",
  'assets/images/neutral/neutral_5.jpg': "Neutral",
  'assets/images/neutral/neutral_6.jpg': "Neutral",
  'assets/images/neutral/neutral_7.jpg': "Neutral",
  'assets/images/neutral/neutral_8.jpg': "Neutral",
  'assets/images/sad/sad_1.jpg': "Sad",
  'assets/images/sad/sad_2.jpg': "Sad",
  'assets/images/sad/sad_3.jpg': "Sad",
  'assets/images/sad/sad_4.jpg': "Sad",
  'assets/images/sad/sad_5.jpg': "Sad",
  'assets/images/sad/sad_6.jpg': "Sad",
  'assets/images/sad/sad_7.jpg': "Sad",
  'assets/images/sad/sad_8.jpg': "Sad",
  'assets/images/surprise/surprise_1.jpg': "Surprise",
  'assets/images/surprise/surprise_2.jpg': "Surprise",
  'assets/images/surprise/surprise_3.jpg': "Surprise",
  'assets/images/surprise/surprise_4.jpg': "Surprise",
  'assets/images/surprise/surprise_5.jpg': "Surprise",
  'assets/images/surprise/surprise_6.jpg': "Surprise",
  'assets/images/surprise/surprise_7.jpg': "Surprise",
  'assets/images/surprise/surprise_8.jpg': "Surprise",
};